version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongodb_data:/data

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongo

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  app:
    container_name: collaborative-editor
    build:
      context: .
    env_file:
      - env/.env
    depends_on:
      - mongo
      - redis
    ports:
      - "8080:8080"
      - "8085:8085"

volumes:
  mongodb_data:

networks:
  default:
    name: backend
