spring:
  application:
    name: 'collab'
  data:
    mongodb:
      uri: '${MONGODB_URI}'
    redis:
      host: '${REDIS_HOST}'
      port: '${REDIS_PORT}'
  profiles:
    active: '${SPRING_PROFILES_ACTIVE}'

management:
  endpoints:
    web:
      exposure:
        include: '*'
  prometheus:
    metrics:
      export:
        enabled: 'true'

server:
  port: '8080'

logging:
  level:
    root: 'info'
    com.example.collab: 'debug'
